package com.market.new_xuxian.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ADDRESS.
 */
public class Address {

    private Long id;
    private String accept_name;
    private String area;
    private String area_id;
    private String city;
    private String city_id;
    private String d_address;
    private String is_default;
    private String l_address;
    private String mobile;
    private Integer sex;
    private Double lat;
    private Double lng;

    public Address() {
    }

    public Address(Long id) {
        this.id = id;
    }

    public Address(Long id, String accept_name, String area, String area_id, String city, String city_id, String d_address, String is_default, String l_address, String mobile, Integer sex, Double lat, Double lng) {
        this.id = id;
        this.accept_name = accept_name;
        this.area = area;
        this.area_id = area_id;
        this.city = city;
        this.city_id = city_id;
        this.d_address = d_address;
        this.is_default = is_default;
        this.l_address = l_address;
        this.mobile = mobile;
        this.sex = sex;
        this.lat = lat;
        this.lng = lng;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccept_name() {
        return accept_name;
    }

    public void setAccept_name(String accept_name) {
        this.accept_name = accept_name;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getArea_id() {
        return area_id;
    }

    public void setArea_id(String area_id) {
        this.area_id = area_id;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCity_id() {
        return city_id;
    }

    public void setCity_id(String city_id) {
        this.city_id = city_id;
    }

    public String getD_address() {
        return d_address;
    }

    public void setD_address(String d_address) {
        this.d_address = d_address;
    }

    public String getIs_default() {
        return is_default;
    }

    public void setIs_default(String is_default) {
        this.is_default = is_default;
    }

    public String getL_address() {
        return l_address;
    }

    public void setL_address(String l_address) {
        this.l_address = l_address;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

}
