package com.market.new_xuxian.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHOPPING_CART_GOODS.
 */
public class ShoppingCartGoods {

    private String cart_goods_nums;
    private String category_type;
    private String down_time;
    private String endtime;
    private String goods_type;
    private String icon;
    private Integer id;
    private String is_del;
    private String main_name;
    private String market_price;
    private String newimg;
    private String newprice;
    private String phonetips;
    private String price;
    private String real_name;
    private String selltype;
    private String show;
    private String soft_no;
    private Integer sold_num;
    private String starttime;
    private Integer store_num;
    private Integer store_nums;
    private String tipsimg;
    private String title;
    private String total_price_one;
    private String unit;
    private String up_time;
    private String userid;
    private Integer account;
    private Long pk;

    public ShoppingCartGoods() {
    }

    public ShoppingCartGoods(Long pk) {
        this.pk = pk;
    }

    public ShoppingCartGoods(String cart_goods_nums, String category_type, String down_time, String endtime, String goods_type, String icon, Integer id, String is_del, String main_name, String market_price, String newimg, String newprice, String phonetips, String price, String real_name, String selltype, String show, String soft_no, Integer sold_num, String starttime, Integer store_num, Integer store_nums, String tipsimg, String title, String total_price_one, String unit, String up_time, String userid, Integer account, Long pk) {
        this.cart_goods_nums = cart_goods_nums;
        this.category_type = category_type;
        this.down_time = down_time;
        this.endtime = endtime;
        this.goods_type = goods_type;
        this.icon = icon;
        this.id = id;
        this.is_del = is_del;
        this.main_name = main_name;
        this.market_price = market_price;
        this.newimg = newimg;
        this.newprice = newprice;
        this.phonetips = phonetips;
        this.price = price;
        this.real_name = real_name;
        this.selltype = selltype;
        this.show = show;
        this.soft_no = soft_no;
        this.sold_num = sold_num;
        this.starttime = starttime;
        this.store_num = store_num;
        this.store_nums = store_nums;
        this.tipsimg = tipsimg;
        this.title = title;
        this.total_price_one = total_price_one;
        this.unit = unit;
        this.up_time = up_time;
        this.userid = userid;
        this.account = account;
        this.pk = pk;
    }

    public String getCart_goods_nums() {
        return cart_goods_nums;
    }

    public void setCart_goods_nums(String cart_goods_nums) {
        this.cart_goods_nums = cart_goods_nums;
    }

    public String getCategory_type() {
        return category_type;
    }

    public void setCategory_type(String category_type) {
        this.category_type = category_type;
    }

    public String getDown_time() {
        return down_time;
    }

    public void setDown_time(String down_time) {
        this.down_time = down_time;
    }

    public String getEndtime() {
        return endtime;
    }

    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }

    public String getGoods_type() {
        return goods_type;
    }

    public void setGoods_type(String goods_type) {
        this.goods_type = goods_type;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getIs_del() {
        return is_del;
    }

    public void setIs_del(String is_del) {
        this.is_del = is_del;
    }

    public String getMain_name() {
        return main_name;
    }

    public void setMain_name(String main_name) {
        this.main_name = main_name;
    }

    public String getMarket_price() {
        return market_price;
    }

    public void setMarket_price(String market_price) {
        this.market_price = market_price;
    }

    public String getNewimg() {
        return newimg;
    }

    public void setNewimg(String newimg) {
        this.newimg = newimg;
    }

    public String getNewprice() {
        return newprice;
    }

    public void setNewprice(String newprice) {
        this.newprice = newprice;
    }

    public String getPhonetips() {
        return phonetips;
    }

    public void setPhonetips(String phonetips) {
        this.phonetips = phonetips;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getReal_name() {
        return real_name;
    }

    public void setReal_name(String real_name) {
        this.real_name = real_name;
    }

    public String getSelltype() {
        return selltype;
    }

    public void setSelltype(String selltype) {
        this.selltype = selltype;
    }

    public String getShow() {
        return show;
    }

    public void setShow(String show) {
        this.show = show;
    }

    public String getSoft_no() {
        return soft_no;
    }

    public void setSoft_no(String soft_no) {
        this.soft_no = soft_no;
    }

    public Integer getSold_num() {
        return sold_num;
    }

    public void setSold_num(Integer sold_num) {
        this.sold_num = sold_num;
    }

    public String getStarttime() {
        return starttime;
    }

    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    public Integer getStore_num() {
        return store_num;
    }

    public void setStore_num(Integer store_num) {
        this.store_num = store_num;
    }

    public Integer getStore_nums() {
        return store_nums;
    }

    public void setStore_nums(Integer store_nums) {
        this.store_nums = store_nums;
    }

    public String getTipsimg() {
        return tipsimg;
    }

    public void setTipsimg(String tipsimg) {
        this.tipsimg = tipsimg;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTotal_price_one() {
        return total_price_one;
    }

    public void setTotal_price_one(String total_price_one) {
        this.total_price_one = total_price_one;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getUp_time() {
        return up_time;
    }

    public void setUp_time(String up_time) {
        this.up_time = up_time;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public Integer getAccount() {
        return account;
    }

    public void setAccount(Integer account) {
        this.account = account;
    }

    public Long getPk() {
        return pk;
    }

    public void setPk(Long pk) {
        this.pk = pk;
    }

}
