package com.market.new_xuxian.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STORE.
 */
public class Store {

    private long id;
    private String area;
    private String area_id;
    private String bdate;
    private String bstarttime;
    private String city_area;
    private String city_id;
    private String city_name;
    private String distance;
    private String firsttime;
    private Double lat;
    private Double lng;
    private String message_alert;
    private String starttime;
    private String telphone;
    private String title;
    private Integer is_click;
    private Integer store_attr;
    private Integer store_status;
    private Integer type;

    public Store() {
    }

    public Store(long id) {
        this.id = id;
    }

    public Store(long id, String area, String area_id, String bdate, String bstarttime, String city_area, String city_id, String city_name, String distance, String firsttime, Double lat, Double lng, String message_alert, String starttime, String telphone, String title, Integer is_click, Integer store_attr, Integer store_status, Integer type) {
        this.id = id;
        this.area = area;
        this.area_id = area_id;
        this.bdate = bdate;
        this.bstarttime = bstarttime;
        this.city_area = city_area;
        this.city_id = city_id;
        this.city_name = city_name;
        this.distance = distance;
        this.firsttime = firsttime;
        this.lat = lat;
        this.lng = lng;
        this.message_alert = message_alert;
        this.starttime = starttime;
        this.telphone = telphone;
        this.title = title;
        this.is_click = is_click;
        this.store_attr = store_attr;
        this.store_status = store_status;
        this.type = type;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getArea_id() {
        return area_id;
    }

    public void setArea_id(String area_id) {
        this.area_id = area_id;
    }

    public String getBdate() {
        return bdate;
    }

    public void setBdate(String bdate) {
        this.bdate = bdate;
    }

    public String getBstarttime() {
        return bstarttime;
    }

    public void setBstarttime(String bstarttime) {
        this.bstarttime = bstarttime;
    }

    public String getCity_area() {
        return city_area;
    }

    public void setCity_area(String city_area) {
        this.city_area = city_area;
    }

    public String getCity_id() {
        return city_id;
    }

    public void setCity_id(String city_id) {
        this.city_id = city_id;
    }

    public String getCity_name() {
        return city_name;
    }

    public void setCity_name(String city_name) {
        this.city_name = city_name;
    }

    public String getDistance() {
        return distance;
    }

    public void setDistance(String distance) {
        this.distance = distance;
    }

    public String getFirsttime() {
        return firsttime;
    }

    public void setFirsttime(String firsttime) {
        this.firsttime = firsttime;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public String getMessage_alert() {
        return message_alert;
    }

    public void setMessage_alert(String message_alert) {
        this.message_alert = message_alert;
    }

    public String getStarttime() {
        return starttime;
    }

    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    public String getTelphone() {
        return telphone;
    }

    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getIs_click() {
        return is_click;
    }

    public void setIs_click(Integer is_click) {
        this.is_click = is_click;
    }

    public Integer getStore_attr() {
        return store_attr;
    }

    public void setStore_attr(Integer store_attr) {
        this.store_attr = store_attr;
    }

    public Integer getStore_status() {
        return store_status;
    }

    public void setStore_status(Integer store_status) {
        this.store_status = store_status;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
