package com.market.new_xuxian.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private String userid;
    private String balance;
    private String birthday;
    private String email;
    private String group_name;
    private String head_ico;
    private String interest;
    private String occupation;
    private String pay_pwd;
    private String payment;
    private String phone;
    private Integer push_count;
    private String push_link;
    private String school;
    private String tocken;
    private String username;
    private String vip_endtime;
    private Integer developersid;
    private Integer exp;
    private Integer group_id;
    private Integer level;
    private Integer point;
    private Integer sex;

    public User() {
    }

    public User(String userid) {
        this.userid = userid;
    }

    public User(String userid, String balance, String birthday, String email, String group_name, String head_ico, String interest, String occupation, String pay_pwd, String payment, String phone, Integer push_count, String push_link, String school, String tocken, String username, String vip_endtime, Integer developersid, Integer exp, Integer group_id, Integer level, Integer point, Integer sex) {
        this.userid = userid;
        this.balance = balance;
        this.birthday = birthday;
        this.email = email;
        this.group_name = group_name;
        this.head_ico = head_ico;
        this.interest = interest;
        this.occupation = occupation;
        this.pay_pwd = pay_pwd;
        this.payment = payment;
        this.phone = phone;
        this.push_count = push_count;
        this.push_link = push_link;
        this.school = school;
        this.tocken = tocken;
        this.username = username;
        this.vip_endtime = vip_endtime;
        this.developersid = developersid;
        this.exp = exp;
        this.group_id = group_id;
        this.level = level;
        this.point = point;
        this.sex = sex;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getBalance() {
        return balance;
    }

    public void setBalance(String balance) {
        this.balance = balance;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getGroup_name() {
        return group_name;
    }

    public void setGroup_name(String group_name) {
        this.group_name = group_name;
    }

    public String getHead_ico() {
        return head_ico;
    }

    public void setHead_ico(String head_ico) {
        this.head_ico = head_ico;
    }

    public String getInterest() {
        return interest;
    }

    public void setInterest(String interest) {
        this.interest = interest;
    }

    public String getOccupation() {
        return occupation;
    }

    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    public String getPay_pwd() {
        return pay_pwd;
    }

    public void setPay_pwd(String pay_pwd) {
        this.pay_pwd = pay_pwd;
    }

    public String getPayment() {
        return payment;
    }

    public void setPayment(String payment) {
        this.payment = payment;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getPush_count() {
        return push_count;
    }

    public void setPush_count(Integer push_count) {
        this.push_count = push_count;
    }

    public String getPush_link() {
        return push_link;
    }

    public void setPush_link(String push_link) {
        this.push_link = push_link;
    }

    public String getSchool() {
        return school;
    }

    public void setSchool(String school) {
        this.school = school;
    }

    public String getTocken() {
        return tocken;
    }

    public void setTocken(String tocken) {
        this.tocken = tocken;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getVip_endtime() {
        return vip_endtime;
    }

    public void setVip_endtime(String vip_endtime) {
        this.vip_endtime = vip_endtime;
    }

    public Integer getDevelopersid() {
        return developersid;
    }

    public void setDevelopersid(Integer developersid) {
        this.developersid = developersid;
    }

    public Integer getExp() {
        return exp;
    }

    public void setExp(Integer exp) {
        this.exp = exp;
    }

    public Integer getGroup_id() {
        return group_id;
    }

    public void setGroup_id(Integer group_id) {
        this.group_id = group_id;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Integer getPoint() {
        return point;
    }

    public void setPoint(Integer point) {
        this.point = point;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

}
